# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml --substitutions _BUCKET='<bucket name>'
steps:
#1: build the get token image
- name: 'docker'
  args: ['build', '-t', '${_IMAGE_NAME}', '.']

#2. Push the container image to Container Registry
- name: 'docker'
  args: ['push', '${_IMAGE_NAME}']


#3. leverage gcloud command to deploy cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '${_RUN_NAME}', '--image', '${_IMAGE_NAME}', 
  '--region', '${_REGION}', '--platform', 'managed', '--allow-unauthenticated', '--port=3000',
  '--service-account=${_SA_MAIL}', '--min-instances=1'] 

# push the image into registry
images:
- ${_IMAGE_NAME}

# _REGION: the region of cloud run deployment
# _IMAGE_NAME: the image name to build contianer and deploy cloud run
# _SA_MAIL: the service acccount bind to the cloud run service
substitutions:
  _REGION: us-central1
  _IMAGE_NAME: gcr.io/cliu201/run_storage_api
  _SA_MAIL: cliu201-sa@cliu201.iam.gserviceaccount.com
  _RUN_NAME: cloudrun-test
tags: ['run_storage_api_in_python']
timeout: 1000s